---
tasks:
- name: features/manage/acknowledge/delete_lines.feature:21
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        bundle exec cucumber --strict features/manage/acknowledge/delete_lines.feature:21
- name: features/manage/hand_over/calendar.feature:7
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        bundle exec cucumber --strict features/manage/hand_over/calendar.feature:7
- name: features/manage/picking_list.feature:42
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        bundle exec cucumber --strict features/manage/picking_list.feature:42
- name: features/manage/take_back/take_back.feature:72
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        bundle exec cucumber --strict features/manage/take_back/take_back.feature:72
- name: features/manage/verification.feature:16
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        bundle exec cucumber --strict features/manage/verification.feature:16
- name: spec/features/manage/serial_number_validation.feature:22
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/serial_number_validation.feature:22
- name: spec/features/manage/serial_number_validation.feature:50
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/serial_number_validation.feature:50
- name: No Tasks for spec/features/borrow
  scripts:
    test:
      body: echo OK
