---
tasks:
- name: No Tasks for features/borrow
  scripts:
    test:
      body: echo OK
- name: spec/features/borrow/model_list.feature:84
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/rspec -r ./spec/steps/borrow/load.rb spec/features/borrow/model_list.feature:84
