---
tasks:
- name: No Tasks for features/borrow
  scripts:
    test:
      body: echo OK
- name: spec/features/borrow/model_list.feature:84
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        bundle exec rspec -r ./spec/steps/borrow/load.rb spec/features/borrow/model_list.feature:84
