---
tasks:
- name: features/borrow/breadcrumb_navigation.feature:27
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/borrow/breadcrumb_navigation.feature:27
