---
tasks:
- name: features/manage/acknowledge/add_item.feature:32
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber --strict features/manage/acknowledge/add_item.feature:32
- name: features/manage/explorative_search.feature:25
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber --strict features/manage/explorative_search.feature:25
- name: features/manage/hand_over/add.feature:37
  scripts:
    test:
      body: |-
        set -eux
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber --strict features/manage/hand_over/add.feature:37
- name: No Tasks for spec/features/manage
  scripts:
    test:
      body: echo OK
