traits:
  Ruby: true

include:
  - cider-ci/task-components/database/configure.yml
  - cider-ci/task-components/database/delete.yml

scripts:

  create-database:
    body: |
      #!/usr/bin/env bash
      set -eux
      if [ -d legacy ]; then cd legacy; fi
      createdb "$DATABASE_NAME"
      psql -d "$DATABASE_NAME" -f ./database/db/structure.sql
      DATABASE_NAME="$DATABASE_NAME" ./database/scripts/restore-seeds

  test:
    start_when:
      database has been created:
        script_key: create-database
