# NOTE: overrides/extands main config for local development
# is merged into main docker-composo.yaml via CLI args: `dc -f docker-compose.yml -f docker-compose.dev.yml`

version: '3'

services:

  legacy:
    build:
      target: dev # stage in Dockerfile
    volumes:
      - ../:/leihs/ # needed so `git` works when checked out as submodule in superproject
      - ../legacy/:/leihs/legacy/ # redundant with the above, but more explicit

  firefox:
    image: selenium/standalone-firefox:97.0-geckodriver-0.30-20220217
    hostname: selenium-firefox
    ports:
      - "4444:4444"
      - "5901:5900" # VNC
      - "7901:7900" # Web-VNC
    environment:
      VNC_NO_PASSWORD: 1
