jobs:

  borrow-scenarios:

    name: 'Borrow: Scenarios'

    description: |
      Run Borrow scenarios under MRI

    include:
      - cider-ci/job-components/run-when-meta-passed.yml

    context:

      task_defaults:
        load: 1.5
        max_trials: 2
        # traits:
        #   ci-g2016-01: true
        include:
          - cider-ci/task-components/database.yml

      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/tasks/borrow-scenarios.yml
