jobs:

  manage-flapping-scenarios:

    name: 'Manage: Flapping Scenarios'

    description: |
      Run Manage flapping scenarios

    include: 
      - cider-ci/job-components/run-when-meta-passed.yml

    context:
      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/shared/flapping-context-configuration.yml
        - cider-ci/tasks/manage-flapping-scenarios.yml
