jobs:

  manage-unstable-scenarios:

    name: 'Manage: Unstable Scenarios'

    description: |
      Run Manage unstable scenarios

    priority: -5

    run_when:
      meta checks have passed:
        type: job
        job_key: meta
        states: [passed]


    context:

      task_defaults:
        load: 1.5
        max_trials: 32
        eager_trials: 2
        include:
          - cider-ci/task-components/database.yml

      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/tasks/manage-unstable-scenarios.yml
