jobs:

  manage-scenarios:

    name: 'Manage: Scenarios'

    priority: 0

    description: |
      Run manage scenarios 

    depends_on:
      include:
        - cider-ci/job-components/preflight-passed.yml
        - cider-ci/job-components/respec-model-passed.yml

    run_when:
      include:
        - cider-ci/job-components/preflight-passed.yml
        - cider-ci/job-components/respec-model-passed.yml

    context:

      task_defaults:
        load: 1.5
        max_trials: 2
        include:
          - cider-ci/task-components/database.yml

      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/tasks/manage-scenarios.yml
