jobs:

  manage-scenarios:

    name: 'Manage: Scenarios'

    priority: 0

    description: |
      Run Manage scenarios under MRI

    include: 
      - cider-ci/job-components/run-when-meta-passed.yml

    context:

      task_defaults:
        load: 1.5
        max_trials: 2
        include:
          - cider-ci/task-components/database.yml
          - cider-ci/task-components/docker-selenium-firefox.yml

      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/tasks/manage-scenarios.yml
