jobs:

  rspec-model-tests:

    name: RSpec Model Tests
    description: Run model specs.

    priority: 1


    depends_on:
      include:
        - cider-ci/job-components/meta-passed.yml
        - cider-ci/job-components/preflight-passed.yml

    run_when:
      include:
        - cider-ci/job-components/meta-passed.yml
        - cider-ci/job-components/preflight-passed.yml


    context:
      generate_tasks:
        include_match: spec/models/.*_spec.rb

      task_defaults:
        max_trials: 2
        include:
          - cider-ci/task-components/database.yml
        scripts:
          test:
            body: |
              #!/usr/bin/env bash
              set -euo pipefail
              unset PGPORT unset PGUSER
              export PGUSER="${PG15USER}"; export PGPORT="${PG15PORT}"
              bundle exec rspec $CIDER_CI_TASK_FILE

      include:
        - cider-ci/shared/main-context.yml

