jobs:

  rspec-model-tests:

    name: RSpec Model Tests
    description: Run model specs.

    priority: 1

    include:
      - cider-ci/job-components/run-when-meta-passed.yml

    context:
      generate_tasks:
        include_match: spec/models/.*_spec.rb

      task_defaults:
        max_trials: 2
        include:
          - cider-ci/task-components/database.yml
        scripts:
          test:
            body: |
              set -eux
              bundle exec rspec $CIDER_CI_TASK_FILE

      include:
        - cider-ci/shared/main-context.yml

